[package]
name = "lakers-nrf52840"
edition = "2021"
version.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
embassy-futures = { git =  "https://github.com/embassy-rs/embassy", branch = "main" }
embassy-sync = { git =  "https://github.com/embassy-rs/embassy", branch = "main", features = ["defmt"] }
embassy-executor = { git =  "https://github.com/embassy-rs/embassy", branch = "main", features = ["task-arena-size-32768", "arch-cortex-m", "executor-thread", "executor-interrupt", "defmt", "integrated-timers"] }
embassy-time = { git =  "https://github.com/embassy-rs/embassy", branch = "main", features = ["defmt", "defmt-timestamp-uptime"] }
embassy-nrf = { git =  "https://github.com/embassy-rs/embassy", branch = "main", features = ["defmt", "nrf52840", "time-driver-rtc1", "gpiote", "unstable-pac", "time"] }
embassy-net = { git =  "https://github.com/embassy-rs/embassy", branch = "main", features = ["defmt", "tcp", "dhcpv4", "medium-ethernet"] }
embassy-usb = { git =  "https://github.com/embassy-rs/embassy", branch = "main", features = ["defmt"] }
embassy-net-esp-hosted = { git =  "https://github.com/embassy-rs/embassy", branch = "main", features = ["defmt"] }
embassy-net-enc28j60 = { git =  "https://github.com/embassy-rs/embassy", branch = "main", features = ["defmt"] }

embedded-io = { version = "0.6.0", features = ["defmt-03"]  }
embedded-io-async = { version = "0.6.1", features = ["defmt-03"] }

defmt = "0.3"
defmt-rtt = "0.4"

fixed = "1.10.0"
static_cell = { version = "2" }
cortex-m = { version = "0.7.6", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7.0"
panic-probe = { version = "0.3", features = ["print-defmt"] }
rand = { version = "0.8.4", default-features = false }
embedded-storage = "0.3.1"
usbd-hid = "0.7.0"
serde = { version = "1.0.136", default-features = false }
embedded-hal = { version = "1.0" }
embedded-hal-async = { version = "1.0" }
embedded-hal-bus = { version = "0.1", features = ["async"] }
num-integer = { version = "0.1.45", default-features = false }
microfft = "0.5.0"

[profile.release]
debug = 2
